### ISSUE TITLE
Roadmap correction

### ISSUE THREAD

**Issue by FernandoRoldan93** [FernandoRoldan93/UrbanBike#22]
Correct the Roadmap of the project following the professor instructions: 
"Roadmap is not linked to US, not composed of different MVP, simply grouping of possibly similar activities. Any project must be deployed, continuously integrated, dockerized and tested. This is not a specific development roadmap"

**Comment by FernandoRoldan93** [comment]
As far as I can figure out from the correction, the problem is that the roadmap should give a MVP on each milestone, that milestone is not just a join of similar activities (like test, docker, CI/CD, etc...) is more about valuable activities or features that will be added to the project. Examples of this could be the following ones: 

- **Management of stations**
  - Get info about one station (occupancy) 
  - Adding stations
  - Store bikes
- **Management of cities**
  - Place stations in a map
  - Get stats about a city (like number of stations and maximum distance between them)
- **Telegram Bot **
  - Check station occupancy in a telegram bot
  - store and rent bikes throw telegram
- **Connect with external API**
  - Get stations data from external API

**Comment by JJ** [comment]
"management of this or that" is not a roadmap. You need to say what product is going to be delivered in that milestone. A "manager"? What will that manager look like? How will you know that manager is what you were looking for? Additionally, and as the milestone description says, US need not be attached permanently to a milestone; they can move from one milestone to the next. Issues, on the other hand, that develop parts of a US will definitely be in a milestone.

**Comment by FernandoRoldan93** [comment]
> "management of this or that" is not a milestone. You need to say what product is going to be delivered in that milestone. A "manager"? What will that manager look like? How will you know that manager is what you were looking for? Additionally, and as the milestone description says, US need not be attached permanently to a milestone; they can move from one milestone to the next. Issues, on the other hand, that develop parts of a US will definitely be in a milestone.

Mmmm... So milestones should be something like "Management of queries about stations through an API" or something like that, something that refers on how the solution will look like and what it will do (Also specified on US's).

**Comment by JJ** [comment]
Well, *that* does not look like a MVP, but yes, it should describe what it will look like (or rather, how will you recongnize it) and what it will do (and how will you know it's doing it right)

**Comment by FernandoRoldan93** [comment]
User histories are missing from roadmap, they have to be linked.

**Comment by JJ** [comment]
Not all of them have to be linked, but yes, you need to show how advancing in one or the other will help you reach one milestone.

**Comment by JJ** [comment]
Please reopen this. I don't know that the commit you've created actually addresses it. With these texts issues it's impossible to check automatically, but you should create a check list to see if it addresses correctly the concerns. Something like "Does it show clearly I understand the concept of milestone and how it's linked to the concept of MVP?" That's for starters, but how HUs are related to each other and related to the problem that needs to be solved is also essential.
Also, Telegram a geolocation are not really a good match. [Check this](https://stackoverflow.com/questions/37983272/telegram-geolocation) Not good to show maps, or things like that.
